#region -------------------------- Templates
$projEXETemplate = 
@"
<!-- generated by https://github.com/HSchwichtenberg/.NETFrameworkTo.NETCoreMigrationPowerShellScript [DATE] -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <RootNamespace>[rootnamespace]</RootNamespace>
    <ApplicationIcon>[icon]</ApplicationIcon>
  </PropertyGroup>

<!-- Assets -->
  <ItemGroup>
[AssetsRef]
  </ItemGroup>

<!-- Nuget Packages -->
  <ItemGroup>
[NugetReference]
  </ItemGroup>

<!-- Projects -->
   <ItemGroup>
[ProjectReference]
   </ItemGroup>

<!-- DLLs -->
  <ItemGroup>
[LibReference]
  </ItemGroup>
</Project>
"@

$projWPFTemplate = 
@"
<!-- generated by https://github.com/HSchwichtenberg/.NETFrameworkTo.NETCoreMigrationPowerShellScript [DATE] -->
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>winexe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <RootNamespace>[rootnamespace]</RootNamespace>
    <ApplicationIcon>[icon]</ApplicationIcon>
  </PropertyGroup>

<!-- Assets -->
  <ItemGroup>
[AssetsRef]
  </ItemGroup>

<!-- Nuget Packages -->
  <ItemGroup>
[NugetReference]
  </ItemGroup>

<!-- Projects -->
   <ItemGroup>
[ProjectReference]
   </ItemGroup>

<!-- DLLs -->
  <ItemGroup>
[LibReference]
  </ItemGroup>
</Project>
"@

$projLibTemplate = 
@"
<!-- generated by https://github.com/HSchwichtenberg/.NETFrameworkTo.NETCoreMigrationPowerShellScript [DATE] -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <RootNamespace>[rootnamespace]</RootNamespace>

  </PropertyGroup>

<!-- Assets -->
  <ItemGroup>
[AssetsRef]
  </ItemGroup>

<!-- Nuget Packages -->
  <ItemGroup>
[NugetReference]
  </ItemGroup>

<!-- Projects -->
   <ItemGroup>
[ProjectReference]
   </ItemGroup>

<!-- DLLs -->
  <ItemGroup>
[LibReference]
  </ItemGroup>
</Project>
"@

$projTestTemplate = 
@"
<!-- generated by https://github.com/HSchwichtenberg/.NETFrameworkTo.NETCoreMigrationPowerShellScript [DATE] -->
<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
 <TargetFramework>netcoreapp3.1</TargetFramework>
 <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
 <Deterministic>false</Deterministic>
 <RootNamespace>[rootnamespace]</RootNamespace>
 <RuntimeIdentifier>win-x64</RuntimeIdentifier>
</PropertyGroup>

<!-- Assets -->
  <ItemGroup>
[AssetsRef]
  </ItemGroup>

<!-- Nuget Packages -->
  <ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
  <PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />
  <PackageReference Include="MSTest.TestFramework" Version="2.0.0" />
  <PackageReference Include="coverlet.collector" Version="1.0.1" />
   <!-- Other Packages -->
[NugetReference]
  </ItemGroup>

<!-- Projects -->
   <ItemGroup>
[ProjectReference]
   </ItemGroup>

<!-- DLLs -->
  <ItemGroup>
[LibReference]
  </ItemGroup>
</Project>
"@

$NugetRefTemplate=
@"
<PackageReference Include="NAME" Version="VERSION" />
"@

$ProjRefTemplate=
@"
<ProjectReference Include="TODO" />
"@

$LibRefTemplate=  
@"
    <Reference Include="TODO">
      <HintPath>..\_Libs\TODO.dll</HintPath>
    </Reference>
"@

$AssetTemplate=
@"
<Resource Include="FILE" />
"@
#endregion # Templates